### ISSUE TITLE
Trying this app on Android Studio

### ISSUE THREAD

**Issue by toplus** [googlesamples/android-FindMyPhone#1]
Hello, I've downloaded this repository and imported the project in Android Studio. When I try to run the app (Wear) I can see "Find my phone" on my Smartwatch, but if I press to activate the alarm on the Smartwatch I can't see and hear anything on the Smartwatch. How can I test this application?

**Comment by naddaf** [comment]
Have you installed the phone part of the app on your phone as well?

**Comment by codingjeremy** [comment]
This sample has been deprecated.
