### ISSUE TITLE
CapabilityListener API

### ISSUE THREAD

**Issue by mgujare** [googlesamples/android-FindMyPhone#2]
Can  CapabilityApi.CapabilityListener API work here ?

https://github.com/googlesamples/android-FindMyPhone/blob/master/Wearable/src/main/java/com/example/android/wearable/findphone/DisconnectListenerService.java#L81-L91

**Comment by codingjeremy** [comment]
For a better example of communicating and using the CapabilityApi, check out the DataLayer, WearVerifyRemoteApp, or the RuntimePermissionsWear Wear samples.

This sample has been deprecated.
